name: Action > Lint

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: $HOME/.sdkman
        key: sdkman-home
    - name: Running java linter
      run: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        '$GITHUB_WORKFLOW_FOLDER/actions/lint/mvn_linter.sh $HOME/JeMPI_Apps'
      shell: bash
    # - name: Running javascript linter
    #   run: './mvn_linter.sh $HOME/JeMPI_Apps'
    #   shell: bash