name: Action > Lint

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/cached-dependencies
    - name: Running java linter
      run: |
        set -eo pipefail
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        source $GITHUB_WORKFLOW_FOLDER/actions/lint/mvn_linter.sh $JEMPI_APP_PATH
      shell: bash
    # - name: Running javascript linter
    #   run: './mvn_linter.sh $HOME/JeMPI_Apps'
    #   shell: bash