name: Prepare

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Cache SDKMan Install
      uses: actions/cache@v4
      with:
        path: ~/.sdkman
        key: sdkman-home
    - name: Set up SDKMan
      uses: ./.github/workflows/actions/install-sdkman
    - name: Set up Java
      uses: ./.github/workflows/actions/sdkman-installer
      with:
        candidate: java
        version: '21.0.1-tem'
    - name: Set up Maven
      uses: ./.github/workflows/actions/sdkman-installer
      with:
        candidate: maven
        version: '3.9.5'
    - name: Set Scala Build Tools
      uses: ./.github/workflows/actions/sdkman-installer
      with:
        candidate: sbt
        version: '1.9.8'