name: Action > Docker Images Build

runs:
  using: 'composite'
  steps:
    - uses: ./.github/workflows/actions/cached-dependencies
    - uses: ./.github/workflows/actions/load-conf-env
    - name: Build Docker Images
      run: |
        set -eo pipefail
        source "$HOME/.nvm/nvm.sh"
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        source $GITHUB_WORKSPACE/devops/linux/docker/conf.env
        pushd $GITHUB_WORKSPACE/JeMPI_Apps
          source ./build-all-ci.sh
        popd
      shell: bash
    