name: Deploy Docker Images
inputs:
  image-build-tag:
    required: true
  docker-push-tag:
    required: false
  docker-host:
    required: true
  docker-username:
    required: true
  docker-password:
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        set -eo pipefail
        source $GITHUB_WORKFLOW_FOLDER/actions/docker-images-deploy/deployDockerImages.sh \
            "${{ inputs.image-build-tag }}" \
            "${{ inputs.docker-push-tag }}" \
            "${{ inputs.docker-host }}" \
            "${{ inputs.docker-username }}" \
            "${{ inputs.docker-password }}"
      shell: bash