name: OnMerge

on:
  pull_request:
    branches:
      - 'dev'
      - 'main'
      - 'master'
    types:
      - closed

env:
  GITHUB_WORKFLOW_FOLDER: ./.github/workflows
  JEMPI_APP_PATH: ./JeMPI_Apps

defaults:
  run:
    shell: bash

jobs:
  prepare:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/prepare
  build-deploy-images:
    runs-on: ubuntu-22.04
    needs: [prepare]
    steps:
    - uses: actions/checkout@v4
    - id: get-image-build-tag
      run: echo "image-build-tag=$(git rev-parse --abbrev-ref HEAD)-$(git log -1 --pretty=format:%h)" >> $GITHUB_OUTPUT
    - uses: ./.github/workflows/actions/build-deploy-images
      with: 
        image-build-tag: ${{ steps.get-image-build-tag.outputs.image-build-tag }}
        docker-host: ${{ vars.DOCKER_LOCAL_HOST_NAME }}
        docker-username: ${{ secrets.DOCKER_LOCAL_USER_NAME }}
        docker-password: ${{ secrets.DOCKER_LOCAL_PASSWORD }}