name: OnPush

on:
  push:
    branches:
      - '*'
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  prepare:
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/prepare
  lint:
    needs: [prepare]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/lint
