name: OnMerge

on:
  push:
    branches:
    - '*'

env:
  GITHUB_WORKFLOW_FOLDER: ~/.github/workflows
  JEMPI_APP_PATH: ~/JeMPI_Apps

defaults:
  run:
    shell: bash

jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/docker-images-build