name: OnPullRequest

on:
  pull_request: 
    branches:
      - '*'
  push:
    branches:
      - '*'

defaults:
  run:
    shell: bash

env:
  GITHUB_WORKFLOW_FOLDER: ./.github/workflows
  JEMPI_APP_PATH: ./JeMPI_Apps
  DEPENDENCIES_HASH: ${{ hashFiles('**/.github/workflows/actions/prepare/action.yml') }}

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/prepare
  lint:
    needs: [prepare]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/lint
  build-check:
    needs: [lint]
    runs-on: ubuntu-22.04
    continue-on-error: ${{ github.ref != 'refs/heads/main' || github.ref != 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/build-check
  test:
    needs: [build-check]
    runs-on: ubuntu-22.04
    continue-on-error: ${{ github.ref != 'refs/heads/main' || github.ref != 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/test
  smoke-test:
    needs: [test]
    runs-on: ubuntu-22.04
    continue-on-error: ${{ github.ref != 'refs/heads/main' || github.ref != 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/smoke-test