name: OnRelease

on:
  release:
    branches:
      - 'main'
      - 'master'
    types: [published]

env:
  GITHUB_WORKFLOW_FOLDER: ./.github/workflows
  JEMPI_APP_PATH: ./JeMPI_Apps

defaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/prepare
  build-deploy-images:
    runs-on: ubuntu-22.04
    needs: [prepare]
    steps:
    - uses: actions/checkout@v4
    - id: validate-tag
      run: |        
          echo "image-build-tag=$(git rev-parse --abbrev-ref HEAD)-$(git log -1 --pretty=format:%h)" >> $GITHUB_OUTPUT
          echo "docker-push-tag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
    - uses: ./.github/workflows/actions/build-deploy-images
      with: 
        image-build-tag: ${{ steps.validate-tag.outputs.image-build-tag }}
        docker-push-tag: ${{ steps.validate-tag.outputs.docker-push-tag }}
        docker-host: "docker.io"
        docker-username: ${{ secrets.DOCKER_HUB_USER_NAME }}
        docker-password: ${{ secrets.DOCKER_HUB_PASSWORD }}