name: OnPullRequest

on:
  pull:
    branches:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  prepare_and_lint:
    uses: ./.github/workflows/entry-on-push.yml
  test:
    needs: [prepare_and_lint]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/test
  smoke-test:
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/smoke-test