name: OnMerge

on:
  merged:
    branches:
      - '*'

env:
  GITHUB_WORKFLOW_FOLDER: $HOME/.github/workflows
  JEMPI_APP_PATH: $HOME/JeMPI_Apps

defaults:
  run:
    shell: bash

jobs:
  build-images:
    uses: $GITHUB_WORKFLOW_FOLDER/build-images.yml
  deploy-images-to-local-repo:
    needs: [build-images]
    uses: $GITHUB_WORKFLOW_FOLDER/deploy-images-to-local-repo.yml