on:
  push:
    branches:
      - '*'

puldefaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up SDKMan
        uses: ./.github/workflows/actions/install-sdkman
      - name: Set up JDK 21.0.1-tem
        run: |
         source "$HOME/.sdkman/bin/sdkman-init.sh"
         sdk install java 21.0.1-tem
      - name: Set up SBT 1.9
        run: |
         source "$HOME/.sdkman/bin/sdkman-init.sh"
         sdk install sbt 1.9

