on:
  push:
    branches:
      - '*'

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 21.0.1-tem
        uses: ./.github/actions/install-java
        with:
          java-version: '21.0.1-tem'
      - name: Set up SBT 1.9
        uses: ./.github/actions/install-sbt
        with:
          sbt-version: '1.9.0'

