name: Save Docker Images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use (defaults to [branch]-[commit])'
        required: false
        type: string

env:
  GITHUB_WORKFLOW_FOLDER: ./.github/workflows
  JEMPI_APP_PATH: ./JeMPI_Apps

defaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/prepare
  save-docker-images:
    runs-on: ubuntu-22.04
    needs: [prepare]
    steps:
    - uses: actions/checkout@v4
    - id: get-image-build-tag
      run: |
          user_tag=${{ inputs.tag }}
          if [ ! -z "$user_tag" ]; then
            echo "image-build-tag=$user_tag" >> $GITHUB_OUTPUT
          else
            echo "image-build-tag=$(git rev-parse --abbrev-ref HEAD)-$(git log -1 --pretty=format:%h)" >> $GITHUB_OUTPUT
          fi
    - uses: ./.github/workflows/actions/docker-images-build
      with:
        image-build-tag: ${{ steps.get-image-build-tag.outputs.image-build-tag }}
    - uses: ./.github/workflows/actions/docker-images-save
      with:
        image-build-tag: ${{ steps.get-image-build-tag.outputs.image-build-tag }}